--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: mailer; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS mailer;




--
-- Name: addresses; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.addresses (
    addressid bigint NOT NULL,
    private_id uuid DEFAULT gen_random_uuid() NOT NULL,
    customerid bigint,
    email character varying(255) NOT NULL,
    name character varying(255),
    first_name character varying(127),
    last_name character varying(127),
    languageid integer DEFAULT 1 NOT NULL,
    verified boolean DEFAULT false NOT NULL,
    needs_review boolean DEFAULT false NOT NULL,
    source character varying(63) DEFAULT 'import'::character varying NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE addresses; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.addresses IS 'Email addresses for mailings';


--
-- Name: COLUMN addresses.private_id; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.addresses.private_id IS 'Private identifier for privacy self-service access';


--
-- Name: COLUMN addresses.customerid; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.addresses.customerid IS 'Owner customer for multi-tenant';


--
-- Name: COLUMN addresses.name; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.addresses.name IS 'Full name (easier than concatenating first+last)';


--
-- Name: COLUMN addresses.needs_review; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.addresses.needs_review IS 'True if name was auto-split and needs manual check';


--
-- Name: COLUMN addresses.source; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.addresses.source IS 'import, scrape, purchase, manual, signup';


--
-- Name: addresses_addressid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.addresses ALTER COLUMN addressid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.addresses_addressid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachments; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.attachments (
    attachmentid bigint NOT NULL,
    contentid bigint NOT NULL,
    filename character varying(255) NOT NULL,
    filepath character varying(511) NOT NULL,
    mimetype character varying(127) DEFAULT 'application/pdf'::character varying NOT NULL
);


--
-- Name: TABLE attachments; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.attachments IS 'Localized attachments per content';


--
-- Name: attachments_attachmentid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.attachments ALTER COLUMN attachmentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.attachments_attachmentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bounces; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.bounces (
    bounceid bigint NOT NULL,
    deliveryid bigint,
    email character varying(255) NOT NULL,
    bounce_type character varying(31) DEFAULT 'hard'::character varying NOT NULL,
    bounce_code character varying(15),
    diagnostic text,
    raw_message text,
    processed boolean DEFAULT false NOT NULL,
    received timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE bounces; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.bounces IS 'Bounce message tracking';


--
-- Name: COLUMN bounces.bounce_type; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.bounces.bounce_type IS 'hard, soft, complaint, delayed';


--
-- Name: COLUMN bounces.bounce_code; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.bounces.bounce_code IS 'RFC 3463 status code (e.g., 5.1.1)';


--
-- Name: bounces_bounceid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.bounces ALTER COLUMN bounceid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.bounces_bounceid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configs; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.configs (
    configid bigint NOT NULL,
    customerid bigint NOT NULL,
    key character varying(63) NOT NULL,
    value text,
    created timestamp with time zone DEFAULT now() NOT NULL,
    modified timestamp with time zone
);


--
-- Name: TABLE configs; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.configs IS 'Per-customer mailer settings';


--
-- Name: COLUMN configs.key; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.configs.key IS 'sender_name, sender_email, reply_to, etc.';


--
-- Name: configs_configid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.configs ALTER COLUMN configid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.configs_configid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deliveries; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.deliveries (
    deliveryid bigint NOT NULL,
    mailid bigint NOT NULL,
    email character varying(255) NOT NULL,
    languageid integer NOT NULL,
    customerid bigint,
    addressid bigint,
    status character varying(31) DEFAULT 'pending'::character varying NOT NULL,
    queued timestamp with time zone DEFAULT now() NOT NULL,
    sent timestamp with time zone,
    error text
);


--
-- Name: TABLE deliveries; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.deliveries IS 'Per-recipient delivery tracking';


--
-- Name: COLUMN deliveries.customerid; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.deliveries.customerid IS 'For customer mailings';


--
-- Name: COLUMN deliveries.addressid; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.deliveries.addressid IS 'For list address mailings';


--
-- Name: COLUMN deliveries.status; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.deliveries.status IS 'pending, queued, sent, failed';


--
-- Name: deliveries_deliveryid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.deliveries ALTER COLUMN deliveryid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.deliveries_deliveryid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imap_servers; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.imap_servers (
    serverid bigint NOT NULL,
    customerid bigint NOT NULL,
    name character varying(127) NOT NULL,
    protocol character varying(7) DEFAULT 'imap'::character varying NOT NULL,
    host character varying(255) NOT NULL,
    port integer DEFAULT 993 NOT NULL,
    encryption character varying(15) DEFAULT 'ssl'::character varying NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    folder character varying(127) DEFAULT 'INBOX'::character varying NOT NULL,
    delete_after_process boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    last_check timestamp with time zone,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE imap_servers; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.imap_servers IS 'IMAP/POP3 servers for bounce processing';


--
-- Name: COLUMN imap_servers.protocol; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.imap_servers.protocol IS 'imap, pop3';


--
-- Name: imap_servers_serverid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.imap_servers ALTER COLUMN serverid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.imap_servers_serverid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: list_addresses; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.list_addresses (
    listid bigint NOT NULL,
    addressid bigint NOT NULL,
    subscribed timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE list_addresses; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.list_addresses IS 'Links addresses to lists';


--
-- Name: lists; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.lists (
    listid bigint NOT NULL,
    customerid bigint,
    name character varying(191) NOT NULL,
    description text,
    is_public boolean DEFAULT false NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE lists; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.lists IS 'Mailing lists for organizing addresses';


--
-- Name: lists_listid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.lists ALTER COLUMN listid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.lists_listid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mail_contents; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.mail_contents (
    contentid bigint NOT NULL,
    mailid bigint NOT NULL,
    languageid integer NOT NULL,
    "from" character varying(255),
    organization character varying(255),
    subject character varying(255) NOT NULL,
    body_md text NOT NULL
);


--
-- Name: TABLE mail_contents; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.mail_contents IS 'Localized mail content (markdown)';


--
-- Name: COLUMN mail_contents."from"; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.mail_contents."from" IS 'Header From display (falls back to config)';


--
-- Name: COLUMN mail_contents.organization; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.mail_contents.organization IS 'Organization header (falls back to config)';


--
-- Name: mail_contents_contentid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.mail_contents ALTER COLUMN contentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.mail_contents_contentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mails; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.mails (
    mailid bigint NOT NULL,
    customerid bigint,
    name character varying(191) NOT NULL,
    is_draft boolean DEFAULT true NOT NULL,
    status character varying(31) DEFAULT 'draft'::character varying NOT NULL,
    scheduled timestamp with time zone,
    started timestamp with time zone,
    completed timestamp with time zone,
    smtp_serverid bigint,
    creator bigint NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL,
    modified timestamp with time zone
);


--
-- Name: TABLE mails; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.mails IS 'Mail campaigns';


--
-- Name: COLUMN mails.is_draft; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.mails.is_draft IS 'Draft flag - not yet ready for sending';


--
-- Name: COLUMN mails.status; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.mails.status IS 'draft, scheduled, sending, completed, cancelled';


--
-- Name: mails_mailid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.mails ALTER COLUMN mailid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.mails_mailid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: smtp_servers; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.smtp_servers (
    serverid bigint NOT NULL,
    customerid bigint NOT NULL,
    name character varying(127) NOT NULL,
    host character varying(255) NOT NULL,
    port integer DEFAULT 587 NOT NULL,
    encryption character varying(15) DEFAULT 'starttls'::character varying NOT NULL,
    username character varying(255),
    password character varying(255),
    auth_method character varying(31) DEFAULT 'plain'::character varying,
    is_default boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE smtp_servers; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.smtp_servers IS 'SMTP servers for outgoing mail';


--
-- Name: COLUMN smtp_servers.encryption; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.smtp_servers.encryption IS 'none, ssl, starttls';


--
-- Name: COLUMN smtp_servers.auth_method; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.smtp_servers.auth_method IS 'plain, login, cram-md5';


--
-- Name: smtp_servers_serverid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.smtp_servers ALTER COLUMN serverid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.smtp_servers_serverid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stats; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.stats (
    statid bigint NOT NULL,
    deliveryid bigint,
    mailid bigint,
    email character varying(255),
    stat_type character varying(31) NOT NULL,
    data jsonb,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE stats; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.stats IS 'Reading and engagement statistics';


--
-- Name: COLUMN stats.stat_type; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.stats.stat_type IS 'open, click, read_onsite, forward, print';


--
-- Name: COLUMN stats.data; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.stats.data IS 'Additional data like URL clicked, user agent, etc.';


--
-- Name: stats_statid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.stats ALTER COLUMN statid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.stats_statid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unsubscriptions; Type: TABLE; Schema: mailer; Owner: -
--

CREATE TABLE mailer.unsubscriptions (
    unsubscriptionid bigint NOT NULL,
    email character varying(255) NOT NULL,
    reason character varying(63),
    token uuid DEFAULT gen_random_uuid() NOT NULL,
    created timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE unsubscriptions; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON TABLE mailer.unsubscriptions IS 'Global unsubscription list';


--
-- Name: COLUMN unsubscriptions.reason; Type: COMMENT; Schema: mailer; Owner: -
--

COMMENT ON COLUMN mailer.unsubscriptions.reason IS 'unsubscribe, bounce, complaint, manual, no_longer_interested, too_many_emails, never_subscribed';


--
-- Name: unsubscriptions_unsubscriptionid_seq; Type: SEQUENCE; Schema: mailer; Owner: -
--

ALTER TABLE mailer.unsubscriptions ALTER COLUMN unsubscriptionid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME mailer.unsubscriptions_unsubscriptionid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses address_customer_email_uq; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.addresses
    ADD CONSTRAINT address_customer_email_uq UNIQUE (customerid, email);


--
-- Name: addresses addresses_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.addresses
    ADD CONSTRAINT addresses_pk PRIMARY KEY (addressid);


--
-- Name: addresses addresses_private_id_uq; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.addresses
    ADD CONSTRAINT addresses_private_id_uq UNIQUE (private_id);


--
-- Name: attachments attachments_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.attachments
    ADD CONSTRAINT attachments_pk PRIMARY KEY (attachmentid);


--
-- Name: bounces bounces_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.bounces
    ADD CONSTRAINT bounces_pk PRIMARY KEY (bounceid);


--
-- Name: configs config_customer_key_uq; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.configs
    ADD CONSTRAINT config_customer_key_uq UNIQUE (customerid, key);


--
-- Name: configs configs_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.configs
    ADD CONSTRAINT configs_pk PRIMARY KEY (configid);


--
-- Name: deliveries deliveries_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.deliveries
    ADD CONSTRAINT deliveries_pk PRIMARY KEY (deliveryid);


--
-- Name: deliveries delivery_mail_email_uq; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.deliveries
    ADD CONSTRAINT delivery_mail_email_uq UNIQUE (mailid, email);


--
-- Name: imap_servers imap_servers_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.imap_servers
    ADD CONSTRAINT imap_servers_pk PRIMARY KEY (serverid);


--
-- Name: list_addresses list_addresses_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.list_addresses
    ADD CONSTRAINT list_addresses_pk PRIMARY KEY (listid, addressid);


--
-- Name: lists lists_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.lists
    ADD CONSTRAINT lists_pk PRIMARY KEY (listid);


--
-- Name: mail_contents mail_content_lang_uq; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mail_contents
    ADD CONSTRAINT mail_content_lang_uq UNIQUE (mailid, languageid);


--
-- Name: mail_contents mail_contents_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mail_contents
    ADD CONSTRAINT mail_contents_pk PRIMARY KEY (contentid);


--
-- Name: mails mails_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mails
    ADD CONSTRAINT mails_pk PRIMARY KEY (mailid);


--
-- Name: smtp_servers smtp_servers_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.smtp_servers
    ADD CONSTRAINT smtp_servers_pk PRIMARY KEY (serverid);


--
-- Name: stats stats_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.stats
    ADD CONSTRAINT stats_pk PRIMARY KEY (statid);


--
-- Name: unsubscriptions unsubscription_email_uq; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.unsubscriptions
    ADD CONSTRAINT unsubscription_email_uq UNIQUE (email);


--
-- Name: unsubscriptions unsubscriptions_pk; Type: CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.unsubscriptions
    ADD CONSTRAINT unsubscriptions_pk PRIMARY KEY (unsubscriptionid);


--
-- Name: addresses_customer_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX addresses_customer_idx ON mailer.addresses USING btree (customerid);


--
-- Name: addresses_email_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX addresses_email_idx ON mailer.addresses USING btree (email);


--
-- Name: addresses_source_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX addresses_source_idx ON mailer.addresses USING btree (source);


--
-- Name: bounces_email_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX bounces_email_idx ON mailer.bounces USING btree (email);


--
-- Name: bounces_received_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX bounces_received_idx ON mailer.bounces USING btree (received);


--
-- Name: configs_customer_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX configs_customer_idx ON mailer.configs USING btree (customerid);


--
-- Name: deliveries_mail_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX deliveries_mail_idx ON mailer.deliveries USING btree (mailid);


--
-- Name: deliveries_status_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX deliveries_status_idx ON mailer.deliveries USING btree (status);


--
-- Name: imap_servers_customer_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX imap_servers_customer_idx ON mailer.imap_servers USING btree (customerid);


--
-- Name: lists_customer_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX lists_customer_idx ON mailer.lists USING btree (customerid);


--
-- Name: mails_customer_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX mails_customer_idx ON mailer.mails USING btree (customerid);


--
-- Name: mails_status_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX mails_status_idx ON mailer.mails USING btree (status);


--
-- Name: smtp_servers_customer_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX smtp_servers_customer_idx ON mailer.smtp_servers USING btree (customerid);


--
-- Name: stats_mail_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX stats_mail_idx ON mailer.stats USING btree (mailid);


--
-- Name: stats_type_idx; Type: INDEX; Schema: mailer; Owner: -
--

CREATE INDEX stats_type_idx ON mailer.stats USING btree (stat_type);


--
-- Name: deliveries address_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.deliveries
    ADD CONSTRAINT address_fk FOREIGN KEY (addressid) REFERENCES mailer.addresses(addressid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: list_addresses address_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.list_addresses
    ADD CONSTRAINT address_fk FOREIGN KEY (addressid) REFERENCES mailer.addresses(addressid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: attachments content_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.attachments
    ADD CONSTRAINT content_fk FOREIGN KEY (contentid) REFERENCES mailer.mail_contents(contentid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: mails creator_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mails
    ADD CONSTRAINT creator_fk FOREIGN KEY (creator) REFERENCES account.users(userid) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: addresses customer_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.addresses
    ADD CONSTRAINT customer_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: configs customer_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.configs
    ADD CONSTRAINT customer_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: deliveries customer_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.deliveries
    ADD CONSTRAINT customer_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: imap_servers customer_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.imap_servers
    ADD CONSTRAINT customer_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: lists customer_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.lists
    ADD CONSTRAINT customer_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: mails customer_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mails
    ADD CONSTRAINT customer_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: smtp_servers customer_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.smtp_servers
    ADD CONSTRAINT customer_fk FOREIGN KEY (customerid) REFERENCES customer.customers(customerid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: bounces delivery_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.bounces
    ADD CONSTRAINT delivery_fk FOREIGN KEY (deliveryid) REFERENCES mailer.deliveries(deliveryid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: stats delivery_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.stats
    ADD CONSTRAINT delivery_fk FOREIGN KEY (deliveryid) REFERENCES mailer.deliveries(deliveryid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: addresses language_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.addresses
    ADD CONSTRAINT language_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: mail_contents language_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mail_contents
    ADD CONSTRAINT language_fk FOREIGN KEY (languageid) REFERENCES public.languages(languageid) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: list_addresses list_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.list_addresses
    ADD CONSTRAINT list_fk FOREIGN KEY (listid) REFERENCES mailer.lists(listid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: deliveries mail_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.deliveries
    ADD CONSTRAINT mail_fk FOREIGN KEY (mailid) REFERENCES mailer.mails(mailid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: mail_contents mail_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mail_contents
    ADD CONSTRAINT mail_fk FOREIGN KEY (mailid) REFERENCES mailer.mails(mailid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: stats mail_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.stats
    ADD CONSTRAINT mail_fk FOREIGN KEY (mailid) REFERENCES mailer.mails(mailid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: mails smtp_server_fk; Type: FK CONSTRAINT; Schema: mailer; Owner: -
--

ALTER TABLE ONLY mailer.mails
    ADD CONSTRAINT smtp_server_fk FOREIGN KEY (smtp_serverid) REFERENCES mailer.smtp_servers(serverid) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--
